# Exported from Render on 2025-01-18T23:36:38Z
services:
- type: web
  name: cmex_poc
  runtime: python
  repo: https://github.com/nextlw/cmex_poc
  plan: starter
  envVars:
  - key: PORT
    sync: false
  - key: COMMAND
    sync: false
  - key: API_TOKEN
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: GOOGLE_API_KEY
    sync: false
  - key: ANTHROPIC_API_KEY
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
  rootDir: backend
version: "1"
