name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - prod
      - desenvolvimento
      - homolog

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          if [ "${GITHUB_REF##*/}" == "prod" ]; then
            npm run build:production
          elif [ "${GITHUB_REF##*/}" == "homolog" ]; then
            npm run build:homolog
          else
            npm run build:development
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist # Ajuste se o diretório de build for diferente
          destination_dir: ${{ github.ref_name }}
          keep_files: true
          publish_branch: gh-pages
